site_name: Geolosys Documentation
repo_url: https://github.com/oitsjustjose/geolosys/
remote_branch: docs
theme: cinder

nav:
  - Home: index.md
  - Ore Generation: OreGeneration.md
  - Config: Config.md
  - CraftTweaker: CraftTweaker.md
  - Download: 'https://www.curseforge.com/minecraft/mc-mods/geolosys'

plugins:
  - search:
      separator: '[\s\-\.]+'
